# Generated by Django 4.2 on 2023-05-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_district_options_alter_province_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='type',
            field=models.CharField(choices=[('W', 'Ward'), ('C', 'Commune'), ('T', 'Town')], default='W', max_length=1),
        ),
    ]
