# Generated by Django 4.2.1 on 2023-05-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='type',
            field=models.CharField(choices=[('C', 'Thành phố'), ('UD', 'Quận'), ('RD', 'Huyện'), ('T', 'Thị xã')], default='UD', max_length=2),
        ),
        migrations.AlterField(
            model_name='province',
            name='type',
            field=models.CharField(choices=[('C', 'Thành phố'), ('P', 'Tỉnh')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='ward',
            name='type',
            field=models.CharField(choices=[('W', 'Phường'), ('C', 'Xã'), ('T', 'Thị trấn')], default='W', max_length=1),
        ),
    ]
