# Generated by Django 4.2.1 on 2023-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_district_type_alter_province_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(default='not set', max_length=255),
            preserve_default=False,
        ),
    ]
