# Generated by Django 4.2.1 on 2023-05-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_region_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='population',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
