# Generated by Django 4.2.1 on 2023-05-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_neighbouringprovince'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='neighbours',
            field=models.ManyToManyField(to='core.province'),
        ),
    ]
