# Generated by Django 4.2.1 on 2023-05-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_province_neighbours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeighbouringProvince',
        ),
    ]
