# Generated by Django 4.2.1 on 2023-05-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_neighbouringprovince'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='is_border',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='district',
            name='is_coastal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='province',
            name='is_border',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='province',
            name='is_coastal',
            field=models.BooleanField(default=False),
        ),
    ]
