# Generated by Django 4.2.1 on 2023-05-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_is_border_n_is_coastal_to_district_n_province_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='is_border',
        ),
        migrations.RemoveField(
            model_name='province',
            name='is_coastal',
        ),
    ]
