# Generated by Django 4.2.5 on 2023-09-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_province_is_border_remove_province_is_coastal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='type',
            field=models.CharField(choices=[('C', 'City (Thành phố)'), ('UD', 'Urban District (Quận)'), ('RD', 'Rural District (Huyện)'), ('T', 'Town (Thị xã)')], default='UD', max_length=2),
        ),
        migrations.AlterField(
            model_name='province',
            name='type',
            field=models.CharField(choices=[('C', 'City (Thành phố)'), ('P', 'Province (Tỉnh)')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='ward',
            name='type',
            field=models.CharField(choices=[('W', 'Ward (Phường)'), ('C', 'Commune (Xã)'), ('T', 'Town (Thị trấn)')], default='W', max_length=1),
        ),
    ]
